name: Build and test

on:
  push:
    branches:
      - master
      - v1
  pull_request:
    branches:
      - master
      - v1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Maven Build and Verify
      run: mvn -B clean verify
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: true
