name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Maven Build and Verify
      run: mvn -B clean verify
    - uses: codecov/codecov-action@v2
      with:
        name: Code coverage report
        fail_ci_if_error: true